FROM python:3.11-alpine

# Set the working directory in the container to /app
WORKDIR /worker

# Copy the rest of the application code to the container
COPY . .

RUN apk add ffmpeg

# Install the dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Define the command to run the Celery APP
CMD celery -A worker.app worker --loglevel INFO